# Change these first
owner: dev-sidem # Your GitHub organization or username, where this repository lives
repo: first-status-page  # The name of this repository

sites:
  - name: Myinnercircle
    url: https://myinnercircle.yannicktchoum.com/
  - name: Mka
    url: mka.thetchoum.com
  - name: App
    url: app.thetchoum.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://thetchoumconsulting.com/wp-content/uploads/2022/02/TTClogo-400x106.png
  name: Upptime
  introTitle: "**thetchoumconsulting**  monitor and status page."
  introMessage: This is a thetchoumconsulting status pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
